In [5]:
from visualizer import calibration
#TODO: import from waveorder
import visual 

from PyQt5 import QtCore

from skimage.io import imread
from skimage.io.collection import alphanumeric_key
from dask import delayed
from glob import glob
import dask.array as da
import matplotlib.pyplot as plt
import numpy as np
import napari
from napari import Viewer
import os

from skimage.registration import phase_cross_correlation
import cv2 as cv
from skimage import io

import cupy as cp 
import imagej

%gui qt 
%matplotlib inline
plt.style.use('dark_background')


In [6]:
main_folder = r'E:\Ed\PSF_defocus\20220404_M25_tamronArray_mfgno11\20220404_M25_PSF1'

# folder = r'E:\Ed\PSF\20220124_M25_allcameras\CAM_Z2'
# file_extension = folder + '/' + '*.raw'
folder_names = sorted(glob(main_folder + '/CAM*/'), key=alphanumeric_key)
offsets_file = os.path.join(main_folder,"offsets.csv")

# file_names = sorted(glob(file_extension),key=alphanumeric_key)

In [7]:
#Scope Parameters
# FOV = 50e-6
cam_px = 5.86e-6
totalmag = 37.5
px_size_img = cam_px/totalmag
zstep = 2e-6
z_scale = zstep/px_size_img

print(px_size_img)
print(zstep/cam_px)
print(z_scale)

1.5626666666666666e-07
0.341296928327645
12.79863481228669


In [8]:
try:
    print("8bit")
    stack= calibration.load_dataset(main_folder,'uint8')
except: 
    print("16bit")
    stack = calibration.load_dataset(main_folder,'uint16')

8bit


In [5]:
# Load offsets from desired folder 
# main_folder = r'E:\Ed\Data\20220324_drosophila_egg\20220324_M25_PSF2-16bit'
main_folder = r'E:\Ed\Data\20220324_drosophila_egg\20220324_M25_PSF1'
offsets_file_load = os.path.join(main_folder,"offsets.csv")
with open(offsets_file_load) as file_name:
    offsets = np.loadtxt(file_name, delimiter=",")

In [ ]:
# px_depth = 'uint16'
# # px_depth = 'uint8'

# raw_M25_volume = [calibration.dask_raw_ds(fd,px_depth) for fd in folder_names]
# stack = da.concatenate(raw_M25_volume, axis=1)
# stack_max_projection= np.array([ da.max(stack[:,i,:,:],axis=0) for i in range(stack.shape[1])])


In [39]:
# viewer=napari.Viewer()
viewer.add_image(stack,scale=[z_scale,1,1])

<Image layer 'stack' at 0x1e5252c7430>

### Get Calibration from Bead's Files

In [9]:
# Generate our own shifted datset
with cp.cuda.Device(0):
    # test = stack[:,11:15,:,:]
    test = stack
    t,c,h,w  = test.shape
    np_mip =[]
    for i in range(c):
        cp_stack = cp.array(test[:,i,:,:])
        cp_mip = cp.max(cp_stack, axis=0)
        np_mip.append(cp.asnumpy(cp_mip))
        cp_mip = None
        cp_stack=None
    np_mip = np.array(np_mip)
    np_mip = np.expand_dims(np_mip,axis=0)
    

In [10]:
# Show the maximum intensity projection
viewer = napari.Viewer()
viewer.add_image(np_mip, name='mip')

<Image layer 'mip' at 0x1a44a181dc0>

In [11]:
#Go to napari and make a square for alignment
crop_region =viewer.layers['Shapes'].data[0]
template = calibration.create_box_ndarray(crop_region)
template_box = template[0:4,2:4]
print(crop_region)
print(template_box)
print(template_box.shape)


[[  0.          12.         279.26535445 357.23111538]
 [  0.          12.         279.26535445 452.80747584]
 [  0.          12.         386.03534271 452.80747584]
 [  0.          12.         386.03534271 357.23111538]]
[[279 357]
 [386 453]]
(2, 2)


In [12]:
# Since OpenCV Match Template takes in uint8 || float32. We can change from uint16 to uint8 easily
np_mip_8bit =visual.im_bit_convert(np_mip,bit=8)
min_val, max_val = template_box
t,c = template[0,0:2]
crop_img = np_mip_8bit[t,c, min_val[0]:max_val[0],min_val[1]:max_val[1]]
viewer.add_image(crop_img,name='crop')

<Image layer 'crop' at 0x1a47aad9a00>

In [13]:
np_mip_8bit[0,i,:,:].shape

(600, 960)

In [14]:
coord =[]
w,h = template.shape  
methods = 'cv.TM_CCOEFF'
print(w,h)
t,c,h,w = np_mip_8bit.shape

for i in range(c):
    method = eval(methods) # This method parses expression and runs ()
    # Apply template Matching
    # Slide through image and compare template patches.
    # Comparison of best matches is foudn as global minn in SQDIFF or max in CCORR or CCOEF.
    res = cv.matchTemplate(np_mip_8bit[0,i,:,:],crop_img,method)
    min_val, max_val, min_loc, max_loc = cv.minMaxLoc(res)
    # If the method is TM_SQDIFF or TM_SQDIFF_NORMED, take minimum
    if method in [cv.TM_SQDIFF, cv.TM_SQDIFF_NORMED]:
        top_left = min_loc
    else:
        top_left = max_loc
        
    bottom_right = (top_left[0] + w, top_left[1] + h)
    #Output would contain the Top left corner and bottom right in case of need to use this rectangle
    coord.append(((top_left[1],top_left[0]),(bottom_right[1],bottom_right[0])))

#For the bead calibration we only use the TL points for alignment
TL_coords = np.array(coord)
TL_coords= TL_coords[0:25,0]

#Coordinates need to then be subtracted to the reference frame (i.e t,c for which rectangle was drawn)
res = []
ref_cam_index = 0
# diff =[]
for i,coordinate in enumerate(TL_coords):
    val = tuple(map(lambda i, j: i - j, TL_coords[ref_cam_index],coordinate))
    res.append(val)
    #If previous values available we can find teh difference between them
    # diff.append(tuple(map(lambda i, j: i + j, val,shift_stack_coord[i])))
# print(diff)
print(res)
# print(shift_stack_coord)
offset_coordinates = np.array(res)

#Save the Offsets in the folder
np.savetxt(offsets_file, offset_coordinates, delimiter=',')

2 4
[(0, 0), (-23, -19), (-39, -190), (-42, -181), (-7, -210), (-19, -108), (3, -90), (7, -88), (-9, -104), (43, -134), (32, -24), (10, -36), (25, -40), (53, -56), (47, -67), (23, -26), (56, -69), (38, -88), (16, -100), (59, -94), (103, -53), (60, -30), (64, -81), (55, -93), (84, -76)]


In [18]:
#Aligning Max Projection to check if coordinates are good

from cupyx.scipy.ndimage import shift
import cupy as cp
# Generate our own shifted datset
with cp.cuda.Device(0):
    mip_aligned = []
    t,c,h,w = stack.shape
    shift_stack_cam = cp.zeros((c,h,w))
    columns = cp.zeros((offset_coordinates.shape[0],1))
    shift_stack_coord = cp.hstack((columns,offset_coordinates))
    print(shift_stack_coord.shape)
    print(np_mip.shape)
    for i in range(c):
        cp_stack = cp.array(np_mip[:,i,:,:])
        shift_stack_cam= shift(cp_stack,shift_stack_coord[i])
        mip_aligned.append(cp.asnumpy(shift_stack_cam))
        cp_stack = None
    mip_aligned = np.array(mip_aligned)
mip_aligned =  np.moveaxis(mip_aligned,0,1)

#Convert to Dask Array
mip_aligned = da.from_array(mip_aligned)
viewer.add_image(mip_aligned, name='MIP_aligned',scale = [z_scale,1,1])

(25, 3)
(1, 25, 600, 960)


<Image layer 'MIP_aligned' at 0x1a461ee1ac0>

In [22]:
from cupyx.scipy.ndimage import shift
import cupy as cp
# Generate our own shifted datset
with cp.cuda.Device(0):
    stack_aligned = []
    t,c,h,w = stack.shape
    shift_stack_cam = cp.zeros((c,h,w))
    columns = cp.zeros((offset_coordinates.shape[0],1))
    shift_stack_coord = cp.hstack((columns,offset_coordinates))
    print(shift_stack_coord.shape)
    print(stack.shape)
    for i in range(c):
        cp_stack = cp.array(stack[:,i,:,:])
        shift_stack_cam= shift(cp_stack,shift_stack_coord[i])
        stack_aligned.append(cp.asnumpy(shift_stack_cam))
        cp_stack = None
    stack_aligned = np.array(stack_aligned)
stack_aligned =  np.moveaxis(stack_aligned,0,1)

#Convert to Dask Array
da_stack_aligned = da.from_array(stack_aligned)
viewer.add_image(da_stack_aligned, name='stack_aligned',scale = [z_scale,1,1])


(25, 3)
(385, 25, 600, 960)


<Image layer 'stack_aligned' at 0x1a58d10a7c0>

### Align Datasets with Known Offsets


In [13]:
from cupyx.scipy.ndimage import shift
import cupy as cp
# Generate our own shifted datset

offset_coordinates = offsets
with cp.cuda.Device(0):
    stack_aligned = []
    t,c,h,w = stack.shape
    shift_stack_cam = cp.zeros((c,h,w))
    columns = cp.zeros((offset_coordinates.shape[0],1))
    shift_stack_coord = cp.hstack((columns,offset_coordinates))
    print(shift_stack_coord.shape)
    print(stack.shape)
    for i in range(c):
        cp_stack = cp.array(stack[:,i,:,:])
        shift_stack_cam= shift(cp_stack,shift_stack_coord[i])
        stack_aligned.append(cp.asnumpy(shift_stack_cam))
        cp_stack = None
    stack_aligned = np.array(stack_aligned)
stack_aligned =  np.moveaxis(stack_aligned,0,1)

(25, 3)
(20, 25, 600, 960)


In [14]:
#Convert numpy to dask?
da_stack_align = da.from_array(stack_aligned)
print(da_stack_align)

dask.array<array, shape=(20, 25, 600, 960), dtype=uint16, chunksize=(20, 25, 300, 320), chunktype=numpy.ndarray>


In [16]:
viewer= napari.Viewer()

Exception in callback BaseAsyncIOLoop._handle_events(6720, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(6720, 1)>
Traceback (most recent call last):
  File "C:\Users\Callisto\Anaconda3\envs\napari-pymmcore\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Callisto\Anaconda3\envs\napari-pymmcore\lib\site-packages\tornado\platform\asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "C:\Users\Callisto\Anaconda3\envs\napari-pymmcore\lib\site-packages\zmq\eventloop\zmqstream.py", line 452, in _handle_events
    self._handle_recv()
  File "C:\Users\Callisto\Anaconda3\envs\napari-pymmcore\lib\site-packages\zmq\eventloop\zmqstream.py", line 481, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\Callisto\Anaconda3\envs\napari-pymmcore\lib\site-packages\zmq\eventloop\zmqstream.py", line 431, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\Callisto\Anaconda3\envs\napa

In [17]:
viewer.add_image(da_stack_align, name='dask_align',scale=[z_scale,1,1])

C:\Users\Callisto\Anaconda3\envs\napari-pymmcore\lib\weakref.py:354: RuntimeWarning: coroutine 'get_msg' was never awaited
  self._pending_removals = []


<Image layer 'dask_align' at 0x18fa1864c40>

In [20]:
# Align the files
ij_stack2  = ij.py.to_java(np.array(da_stack_align,dtype='uint16'))
ij.ui().show('PSF', ij_stack2)

### CROP PSF TO ANALYZE


In [23]:
#Go to napari and make a square for alignment
crop_region =viewer.layers['Shapes'].data[0]
template = calibration.create_box_ndarray(crop_region)
template_box = template[0:4,2:4]
print(crop_region)
print(template_box)
print(template_box.shape)

[[192.          12.         346.22491219 314.85478602]
 [192.          12.         346.22491219 420.44183099]
 [192.          12.         429.58310559 420.44183099]
 [192.          12.         429.58310559 314.85478602]]
[[346 315]
 [430 420]]
(2, 2)


In [25]:
# Since OpenCV Match Template takes in uint8 || float32. We can change from uint16 to uint8 easily
# np_mip_8bit =visual.im_bit_convert(np_mip,bit=8)
min_val, max_val = template_box
t,c = template[0,0:2]
print(t,c)
crop_img = da_stack_aligned[:,:, min_val[0]:max_val[0],min_val[1]:max_val[1]]
# crop_img = np_mip_8bit[t,c, min_val[0]:max_val[0],min_val[1]:max_val[1]]
viewer.add_image(crop_img,name='crop')

192 12


<Image layer 'crop' at 0x1a47ac28070>

In [17]:
crop_img

dask.array<getitem, shape=(385, 25, 10, 12), dtype=uint8, chunksize=(175, 25, 10, 12), chunktype=numpy.ndarray>

### Image J Part

In [26]:
def start_imagej():
    import imagej
    global ij
    ij = imagej.init('net.imagej:imageJ:2.1.0',mode='interactive')
    ij.ui().showUI()
    print(ij.getVersion())

QtCore.QTimer.singleShot(0, start_imagej)

2.1.0/1.53c


In [27]:
# Align the files
ij_stack2  = ij.py.to_java(np.array(crop_img,dtype='uint8'))
ij.ui().show('PSF', ij_stack2)

In [49]:
b =ij.WindowManager.getWindow('PSF-2')

In [53]:
ij.WindowManager.setWindow(b)
a =ij.WindowManager.getCurrentImage()
anp = ij.py.from_java(a)
print(anp.shape)
anp2 = anp[:,:,:,:,np.newaxis]
print(anp2.shape)
anp2 = np.swapaxes(anp,1,4)
anp2.shape


(385, 9, 8, 25)


TypeError: invalid indexer array, does not have integer dtype: array(None, dtype=object)

In [48]:
print(anp2.shape)
visual.image_stack_viewer(anp2)

(385, 25, 10, 10)


interactive(children=(IntSlider(value=0, description='stack_idx_1', max=384), IntSlider(value=0, description='…

<function visual.image_stack_viewer.<locals>.interact_plot_4D(stack_idx_1, stack_idx_2)>

SyntaxError: invalid syntax (1059654506.py, line 1)

In [4]:
# def start_imagej():
#     global ij
#     import imagej
#     ij = imagej.init(r'C:\Users\Callisto\Documents\edhirata\software\Fiji.app',mode='interactive')
#     ij.ui().showUI()
#     print(ij.getVersion())
    
# QtCore.QTimer.singleShot(0, start_imagej)

sys:1: RuntimeWarning: coroutine 'get_msg' was never awaited


In [19]:
# os.environ['JAVA_HOME'] = r'C:\Users\Callisto\Anaconda3\envs\napari-pymmcore'